#name: Your New Jekyll Site
name: satoso.net
domain: satoso.net
description: "佐藤奏のウェブサイト。"
baseurl: ""
feed_file: "/feed.xml"
url: "http://satoso.net"
markdown: redcarpet
#pygments: true
highlighter: pygments
exclude: [README.markdown, commit-push.sh, jekyll-serve.sh]
include: [.htaccess]
#gems: [jekyll-slim, jekyll-sass]
gems: [jekyll-slim]
permalink: /text/:year/:month/:day/:title.html
twitter_username: "@so_trb"
googleplus_profile_url: "https://plus.google.com/117220374295498294715/"
sass:
  style: :expanded
##for jekyll-sass
#sass:
#    style:  expanded  # nested|expanded|compact|compressed
#    # deploy_style: compressed  # nested|expanded|compact|compressed
#    deploy_style: expanded # nested|expanded|compact|compressed
#    # "deploy_style:" is used only for building the site
#    # (ie: not using the --watch flag)
#
#    compile_in_place: false   # true|false
#    # If true, compiles sass directly into your jekyll source directory
#    # As well as your destination directory
