# Where things are
source: ./_source
destination: ./_site

# Handling Reading
include: [.htaccess, .gitkeep]
exclude: []

# Plugins
# gems: [jekyll-slim]

# Conversion
markdown: redcarpet
highlighter: pygments
sass:
  style: :expanded

# Serving
baseurl: ""

# Outputting
permalink: /texts/:year:month:day-:title/

# Original parameters
title: satoso.net
domain: satoso.net
description: "佐藤奏のウェブサイト。"
feed_file: "/feed.xml"
feed_file_diary: "/diary/index.rss"
url: "http://satoso.net"
twitter_username: "@so_trb"
googleplus_profile_url: "https://plus.google.com/117220374295498294715"

# Defaults
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
  -
    scope:
      path: 'about'
    values:
      under: about
  -
    scope:
      path: 'diary'
    values:
      under: diary
      layout: null
  -
    scope:
      path: 'texts'
    values:
      under: texts
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      under: texts
      og:
        type: article
  -
    scope:
      path: 'misc'
    values:
      layout: default
      under: misc
